### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by andyyuan78** [shangjingbo1226/AutoNER#10]
(py3env) gpuws@gpuws32g:~/ub16_prj/AutoNER$ CUDA_VISIBLE_DEVICES=0 python3 train_partial_ner.py --cp_root models/BC5CDR/checkpoint/   --checkpoint_name autoner
[2018-11-05 07:42:13,004] Checkpoint Folder Already Exists: models/BC5CDR/checkpoint/autoner
[2018-11-05 07:42:13,004] Input 'yes' to confirm deleting this folder; or 'no' to exit.
yes for delete or no for exit: yes
[2018-11-05 07:42:16,398] Saving system environemnt and python packages
[2018-11-05 07:42:16,709] It's recommended to set ``CUDA_DEVICE_ORDER``to be ``PCI_BUS_ID`` by ``export CUDA_DEVICE_ORDER=PCI_BUS_ID``;otherwise, it's not guaranteed that the gpu index frompytorch to be consistent the ``nvidia-smi`` results.
Traceback (most recent call last):
  File "train_partial_ner.py", line 61, in <module>
    gpu_index = pw.auto_device() if 'auto' == args.gpu else int(args.gpu)
  File "/home/gpuws/py3env/lib/python3.5/site-packages/torch_scope/wrapper.py", line 530, in auto_device
    return basic_wrapper.auto_device(metrics = metrics, logger = self.logger, use_logger = use_logger, required_minimal = required_minimal, wait_time = wait_time)
  File "/home/gpuws/py3env/lib/python3.5/site-packages/torch_scope/wrapper.py", line 250, in auto_device
    memory_list = basic_wrapper.nvidia_memory_map(logger = logger)
  File "/home/gpuws/py3env/lib/python3.5/site-packages/torch_scope/wrapper.py", line 175, in nvidia_memory_map
    '--format=csv,noheader'], encoding='utf-8')
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'
(py3env) gpuws@gpuws32g:~/ub16_prj/AutoNER$

**Comment by LiyuanLucasLiu** [comment]
We just checked the api, upgrading to ```python>=3.6``` could solve this problem. Later we would update the ```torch-scope``` package for better compatibility.
